### ISSUE TITLE
Some sites are broken after v3.0.0 update

### ISSUE THREAD

**Issue by 54m4d** [ChristopherBull/Clear-Links#13]
Hello Christopher, happy to see some activity after a prolonged absence, Great extension!

I observed that the extension is causing a malfunction on at least one website I encountered after the v3.0.0 update.

The issue arises when the extension is active, preventing the site from loading/displaying some fields and a green button. However, when the extension is disabled, they are loaded/displayed as expected.

To replicate the problem, you can visit the mentioned [site](https://www.finansportalen.no/bank/bankinnskudd). If you observe a never-ending spinning wheel, that indicates the issue. Please try disabling the extension and check for any noticeable differences.

I hope you get the opportunity to take a look at this issue.

Thanks!

**Comment by 54m4d** [comment]
Hi! This is just in time as I recently encountered the same issue on some other websites.

Thanks for the quick fix.

**Comment by 54m4d** [comment]
@ChristopherBull I just tested v3.1.0 and I encountered a minor issue where hyperlinks transform into "clickable/selectable" text. This anomaly occurs primarily during the initial hover, but it can also manifest after multiple back-and-forth hovers, indicating a somewhat inconsistent behavior.

I was able to reproduce the issue on https://github.com/issues

As you can see below, the cursor turned from a hand to a text-select cursor. This should normally be a clickable link.

![Capture 04_01_2024 16_39_30](https://github.com/ChristopherBull/Clear-Links/assets/52612348/497ed6b1-33ed-4fc5-bbe2-edd0cb9885ab)

**Comment by ChristopherBull** [comment]
> @ChristopherBull I just tested v3.1.0 and I encountered a minor issue where hyperlinks transform into "clickable/selectable" text. This anomaly occurs primarily during the initial hover, but it can also occur after multiple back-and-forth hovers, indicating a somewhat inconsistent behavior.
> 
> I was able to reproduce the issue on https://github.com/issues
> 
> As you can see below, the cursor turned from a hand to a text-select cursor. This should normally be a clickable link.
> 
> ![Capture 04_01_2024 16_39_30](https://private-user-images.githubusercontent.com/52612348/294230051-497ed6b1-33ed-4fc5-bbe2-edd0cb9885ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzODc0MTYsIm5iZiI6MTcwNDM4NzExNiwicGF0aCI6Ii81MjYxMjM0OC8yOTQyMzAwNTEtNDk3ZWQ2YjEtMzNlZC00ZmM1LWJiZTItZWRkMGNiOTg4NWFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDE2NTE1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhZjM1OWFhMGZmMjQwYzNmMDU1YzEwODUxZDZmNTNhOGQ0NTk4YmU5ZTdiNDVmMTJhOTIwMDU3M2FiNDkwYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XGU_wsMvqx54DF4apYltXkR3retybOidKfUO9pSf8Qs)

Ok, thanks for sharing. Please create a new issue for this, as it appears to be a separate issue. I will try to re-create the problem.
