### ISSUE TITLE
Add custom style/theme for links to external domains

### ISSUE THREAD

**Issue by 54m4d** [ChristopherBull/Clear-Links#17]
Hi!

When `Only for links to external domains` is enabled, customization of the style/theme is unavailable for links to external domains.

By introducing an option to customize the style/theme of external domain links, the user experience will be enhanced.

**Comment by ChristopherBull** [comment]
Hi, thanks for the suggestion. I could not replicate this issue so I will be closing this issue, however, I have considered the enhancement you suggested:

I will not be adding style customisation based on link types at this time. However, I have noted an enhancement to add an option to add an icon or some form of indication that a link is external (#18). If the tooltip is showing for all links (not just external), there could be an extra option to show an icon (for example) to indicate that the link is external.
